### PR TITLE
fix service handling (should be compatible with most Linux distributi…

### PR DESCRIPTION
**Pull request by ghost**
…ons nowadays)

### CODE REVIEW

**Comment by hoonetorg** [comment]
This works also with systemd on el7 distries.
service mysql start/stop will be redirected to systemctl start/stop mysql.
should be the same for Debian, Ubuntu 16.04+

**Comment by deviantony** [comment]
Thanks for the PR but I'm not sure if I should merge it because I think it can cause issues on older distributions.

**Comment by hoonetorg** [comment]
I understand your concerns about backward compatibility. 
On the other hand all major distributions switched to systemd now and there restoring backups with pyxtrabackup must be broken, am I wrong?
The "service" command can be used on sysv and systemd as I said.
A colleague told me a Debian Lenny would not have a service command (I did not verify :) ).

Probably it's better to 
- check, which init system is used and create the appropriate command then or
- fail restoration if a mysql server process runs(then the user must manually stop mysql process before restoration)

For me it is fixed (I compiled an rpm for el7 with the fix and put it in a repo :) )

**Comment by deviantony** [comment]
I've started to debate about this in #32 

And from that comment https://github.com/deviantony/xtrabackup-scripts/issues/32#issuecomment-159010689

I do not want to add more code to manage service handling depending on the system.

In order to work with the majority of systems, I think that it would be better to let the user manage the service by himself. I'd accept a PR to remove the service management from the tool and let the user manage the service with an updated procedure.

In the meantime, I'll merge your PR as, as you said, most new distros should support it.

**Comment by deviantony** [comment]
Released and pushed to pypi.

**Comment by hoonetorg** [comment]
:+1:

**Pull request merged**
